2025-02-24 09:42:14,353 INFO: Microblog startup [in C:\Users\alvar\Programacion\proyectos\Microblog-2\app\__init__.py:28]
2025-02-24 09:42:43,933 ERROR: Exception on /edit_profile [POST] [in c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\alvar\Programacion\proyectos\Microblog-2\app\routes.py", line 91, in edit_profile
    db.session.commit()
    ~~~~~~~~~~~~~~~~~^^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 599, in commit
    return self._proxied.commit()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 85, in save_obj
    _emit_update_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        update,
        ^^^^^^^
    )
    ^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
        statement, multiparams, execution_options=execution_options
    )
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\alvar\Programacion\proyectos\Microblog-2\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('susan', "Hi there, there's vareto but you can call me warell!", 3)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-02-24 13:04:40,169 INFO: Microblog startup [in C:\Users\alvar\Programacion\proyectos\Microblog-2\app\__init__.py:28]
2025-02-25 12:38:10,008 INFO: Microblog startup [in C:\Users\alvar\programacion\proyectos\Microblog-2\app\__init__.py:28]
2025-02-26 15:56:23,847 INFO: Microblog startup [in C:\Users\alvar\Programacion\proyectos\Microblog-2\app\__init__.py:38]
2025-02-26 15:56:43,132 INFO: Microblog startup [in C:\Users\alvar\Programacion\proyectos\Microblog-2\app\__init__.py:38]
2025-02-26 15:57:32,589 INFO: Microblog startup [in C:\Users\alvar\Programacion\proyectos\Microblog-2\app\__init__.py:38]
2025-02-26 15:57:52,657 INFO: Microblog startup [in C:\Users\alvar\Programacion\proyectos\Microblog-2\app\__init__.py:38]
2025-02-26 17:25:39,153 INFO: Microblog startup [in C:\Users\alvar\Programacion\proyectos\Microblog-2\app\__init__.py:40]
2025-02-26 17:26:24,610 INFO: Microblog startup [in C:\Users\alvar\Programacion\proyectos\Microblog-2\app\__init__.py:40]
2025-02-26 17:26:51,225 ERROR: Esto es un mensaje de error de prueba [in C:\Users\alvar\Programacion\proyectos\Microblog-2\app\routes.py:166]
2025-02-26 17:34:03,224 INFO: Microblog startup [in C:\Users\alvar\Programacion\proyectos\Microblog-2\app\__init__.py:40]
2025-02-26 17:36:16,753 INFO: Microblog startup [in C:\Users\alvar\Programacion\proyectos\Microblog-2\app\__init__.py:40]
2025-02-26 17:36:59,278 INFO: Microblog startup [in C:\Users\alvar\Programacion\proyectos\Microblog-2\app\__init__.py:40]
2025-02-26 17:37:05,535 ERROR: Esto es un mensaje de error de prueba [in C:\Users\alvar\Programacion\proyectos\Microblog-2\app\routes.py:166]
2025-02-26 18:19:42,395 INFO: Microblog startup [in C:\Users\alvar\Programacion\proyectos\Microblog-2\app\__init__.py:29]
